eureka:
  instance:
    hostname: h1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://h2:8081/eureka/

server:
  port: 8080
spring:
  application:
    name: eureka-server
