# Seata Server 配置

# 事务分组映射
service.vgroupMapping.seata-at-sample=default

# 存储模式
store.mode=file

# 文件存储配置
store.file.dir=file_store/data
store.file.max-branch-session-size=16384
store.file.max-global-session-size=512
store.file.file-write-buffer-cache-size=16384
store.file.flush-disk-mode=async
store.file.session-commit-read-buffer-size=16384
store.file.lock.retry-times=30
store.file.lock.retry-interval-long=10000
